language: node_js
node_js:
- stable
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
- .ci/lerna.sh
script:
- npm run publish -- --git-remote=ci
env:
  global:
  - secure: StxSoG6ztr2RnH58Egxd8RekCU9DZTxyhcDmHISiFAPLL04dtnI/PLiyqvGC07UfYKaal99evkdmBRXY8EJFldj9Cs8rgx2SbNT3zjXzM1FPtiIIAa27LIttwiWSwul596lxgznxd5ByZExg46OMSghDrjzvRZA/zkqn3pXfsbnMDkGyycpUv6yir4R7I4yy/NsGXNl2kwKnJznlW4h9YhNAJrmr6qkc3bBTrpyd331mUmMJ8q7DzIb1kqaRjwBumADHSrGCmmRQVD1g3wBprlSmBVQOcBzkFAddc5Hn6yfFkLlvhYAdB+fI6nKM5U9umawTq0kPPgSbMxcvFQ/G0jxee2TvyJnXF4Kfbzhn2hpsEM0DKP3do4nfANTMKXVqUkOankhT3CoeZStdyhC+KpfKIpWXydnC6td0Iso8/v9N6oyQ54W0lT4PeXpNJNw7VJJDtUndWqVz7bT8DyODcMNPKZiQdgbimB6q/55eU7aDj4bWotGgDxiTmdaCEe0OYKpCYkO4xN3BCjCc7urMXevrO8wb/2Ehq9zxzly5Q+f9xNb8qyJCcDStQebXSlceXnujthNajk0E70XQOQKr3p21bSKgzNh0vIaK/Dq3aNDcDTJa4/SbB+992CmK5E9CDOW6T5l+Qk8/rMQJv42rOhdiFUkzfKDTSk9l7UMAbaI=
  - secure: e1la7AumJL8LUcYzFiY+6fnk/UiCCFbtbSlQPyF/65G7faS96hoAOPqVFoL8d/1LxuwyAmdlijivgYOFxbgTex5ZlvMg2rFap/zzhf0WUGoOfzS8xS9AuC2KiV5OF0dqsOVfr3Lm6wCxXc+cJhk9rO7+BisDIWFiKTpdJtBX5ucywLl2E6ruR8a6vLEYL8CVBSzdNnEDLMZaJ/E24QwFzSRPSkGNABFQMWVnsbawoTQ7Nid0aReX2CkEix0t9VqXRsyLtwyODRNA7HGVkGLedSj1NBI6RWTuO+fWlwhAXhPYOjR/HCJLYkjmQuww3Ek1yDv3E5L0ND+tN1BaKamqDkpFi2IP/cm0WjSOM0lpr4TUiSymXhBegLX6tfrWIxXz4sLKeEOQBqD9pMSyzFfrFMEk9dVGnw6M4v2razKduiAmMV+i06fFd5Pozusv3jf1142jMf80SjX8gYXxGjgHrPqD1fAKpH93kPxH8guYKovqgUgtUMCXUGW1YZNY1ypc/0+RWNNy805ni9XgBOFiAkcTbInTFJBH1E4qcCSkgFfk6Ivonqt7sA5C9CE9tBSb4cTV5txwjSb86I4rNPPf3Ya5FTJBf/L9Bh68nVrSHXXFTmTOj8JQDYEB0HHlCrp2Gc/TouVUXruwUXf7+unwP0TO1wXmGeWPSfqWD96aTzA=
